name: Deploy Hello World App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Gunicorn version
      run: |
        pip install gunicorn
        gunicorn --version
        
    - name: Run tests
      run: |
        # You can add test commands here if needed
    
    - name: Debug application run
      run: |
        pwd  # Print the current working directory
        ls   # List the contents of the current directory
        gunicorn --chdir app.py -b 0.0.0.0:8000 app:app
